"""
Minimum Domino version supported by this python-domino library
"""

MINIMUM_SUPPORTED_DOMINO_VERSION = '4.1.0'

DOMINO_TOKEN_FILE_KEY_NAME = 'DOMINO_TOKEN_FILE'
DOMINO_USER_API_KEY_KEY_NAME = 'DOMINO_USER_API_KEY'
DOMINO_HOST_KEY_NAME = 'DOMINO_API_HOST'
