repos:
  - repo: local
    hooks:
      - id: check-snake-case
        name: Check snake_case naming
        entry: python scripts/check_snake_case.py
        language: python
        files: ^domino/.*\.py$
        exclude: ^domino/_impl/|^domino/airflow/
        pass_filenames: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: [-b, master]
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args:
          [
            --no-warn-no-return,
            --namespace-packages,
            --explicit-package-bases,
            --ignore-missing-imports,
            --follow-imports=silent,
            --python-version=3.10,
          ]
        additional_dependencies:
          - "types-pyyaml"
          - "types-requests"
          - "types-retry"
          - "types-pytz"
          - "types-tabulate"
          - "types-python-dateutil"
          - "types-redis"
          - "types-protobuf"
          - "types-frozendict"
          - "types-typing-extensions"
          - "types-urllib3"
