[tox]
envlist = py310,py311,py312,nosdk

[testenv]
usedevelop = true
deps =
    pytest>=7.4.3
    pytest-cov>=5.0.0
    requests-mock>=1.9.3
    docker>=7.1.0
    pytest-mock>=3.14.1
commands =
    pytest tests/ \
        --ignore=tests/agents \
        --ignore=tests/integration \
        --ignore=tests/scripts \
        --ignore=tests/test_operator.py \
        --ignore=tests/test_spark_operator.py \
        -v --tb=short \
        --cov=domino \
        --cov-report=term-missing \
        {posargs}

[testenv:nosdk]
usedevelop = true
deps =
    pytest>=7.4.3
    requests-mock>=1.9.3
setenv =
    DATA_SDK = no
commands =
    pytest tests/test_data_sources_nods.py -v {posargs}
