# coding: utf-8

"""
    Domino Public API

    Public API endpoints for Custom Metrics  # noqa: E501

    The version of the OpenAPI document: 5.3.0
    Generated by: https://openapi-generator.tech
"""

import unittest

from domino._impl.custommetrics import configuration


class TestInvalidBodyEnvelopeV1(unittest.TestCase):
    """InvalidBodyEnvelopeV1 unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
