# coding: utf-8

"""
    Domino Public API

    Public API endpoints for Custom Metrics  # noqa: E501

    The version of the OpenAPI document: 5.3.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import domino._impl.custommetrics
from domino._impl.custommetrics.model.target_range_v1 import TargetRangeV1
from domino._impl.custommetrics import configuration


class TestTargetRangeV1(unittest.TestCase):
    """TargetRangeV1 unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
