# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import domino._impl.custommetrics
from domino._impl.custommetrics.paths.api_metric_alerts_v1 import post  # noqa: E501
from domino._impl.custommetrics import configuration, schemas, api_client

from .. import ApiTestMixin


class TestApiMetricAlertsV1(ApiTestMixin, unittest.TestCase):
    """
    ApiMetricAlertsV1 unit test stubs
        Send a metric alert  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200
    response_body = ''




if __name__ == '__main__':
    unittest.main()
