# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import domino._impl.custommetrics
from domino._impl.custommetrics.paths.api_metric_values_v1_model_monitoring_id_metric import get  # noqa: E501
from domino._impl.custommetrics import configuration, schemas, api_client

from .. import ApiTestMixin


class TestApiMetricValuesV1ModelMonitoringIdMetric(ApiTestMixin, unittest.TestCase):
    """
    ApiMetricValuesV1ModelMonitoringIdMetric unit test stubs
        Retrieve metric values  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
