# coding: utf-8

"""


Generated by: https://openapi-generator.tech
"""

import unittest

from domino._impl.custommetrics import api_client, configuration
from domino._impl.custommetrics.paths.api_metric_values_v1 import post  # noqa: E501

from .. import ApiTestMixin


class TestApiMetricValuesV1(ApiTestMixin, unittest.TestCase):
    """
    ApiMetricValuesV1 unit test stubs
        Log metric values  # noqa: E501
    """

    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 201
    response_body = ""


if __name__ == "__main__":
    unittest.main()
