# coding: utf-8

"""
    Domino Public API

    Public API endpoints for Custom Metrics  # noqa: E501

    The version of the OpenAPI document: 5.3.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from domino._impl.custommetrics import schemas  # noqa: F401


class NewMetricValuesEnvelopeV1(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "newMetricValues",
        }
        
        class properties:
            
            
            class newMetricValues(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['NewMetricValueV1']:
                        return NewMetricValueV1
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['NewMetricValueV1'], typing.List['NewMetricValueV1']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'newMetricValues':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'NewMetricValueV1':
                    return super().__getitem__(i)
            __annotations__ = {
                "newMetricValues": newMetricValues,
            }
    
    newMetricValues: MetaOapg.properties.newMetricValues
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["newMetricValues"]) -> MetaOapg.properties.newMetricValues: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["newMetricValues", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["newMetricValues"]) -> MetaOapg.properties.newMetricValues: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["newMetricValues", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        newMetricValues: typing.Union[MetaOapg.properties.newMetricValues, list, tuple, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'NewMetricValuesEnvelopeV1':
        return super().__new__(
            cls,
            *args,
            newMetricValues=newMetricValues,
            _configuration=_configuration,
            **kwargs,
        )

from domino._impl.custommetrics.model.new_metric_value_v1 import NewMetricValueV1
