name: docs

on:
  push:
    #tags: [ 'v*', 'release-*' ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0     # required for sphinx-multiversion to see history
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Add pipenv
        run: pip install pipenv

      - name: Install doc build deps
        run: |
          pipenv --python 3.10 install ".[dev]"
          pipenv --python 3.10 install ".[data,airflow,aisystems]"

      - name: Build multi-version docs
        run: |
          BRANCH=niole.DOM-70876.docs
          RELEASE_TAG_PATTERN=niole.DOM-70876.docs

          git fetch origin
          git fetch origin --tags

          pipenv run sphinx-multiversion source docs_build \
            -D smv_branch_whitelist=$BRANCH smv_released_pattern=$RELEASE_TAG_PATTERN

      - name: Assemble site and landing page
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p site
          rsync -a docs_build/html/ site/
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
